### ISSUE TITLE
Documentation on cli?

### ISSUE THREAD

**Issue by IanVaughan** [jf/rbenv-gemset#27]
The readme completely missing out any info regarding the rbenv gemset command set, what to do with it, when to use them, etc etc.

**Comment by neovatar** [comment]
Sorry it took me so long to answer: I discontinued using gemsets in favor of bundler based workflows. So probably someone who is actually using rbenv-gemsets may want to help out.

**Comment by radriaanse** [comment]
How much is rbenv-gemset actually used now ? I like to work with it but I'm reading all over the place that it's preferred to use bundler. 
If still used, I would like to help out with the doc's though.

**Comment by jf** [comment]
I don't collect metrics, but I do know it is used actively, including last I heard, by the customers at one particular large hosting company.

I have a quite a few things to say, but in the interest of better communication and time, I'll give them in point form:

* `rbenv-gemset` is cleaner than `bundler` IMO.
* It *can* also be used together with `bundler` (so `bundler` *documents* the gems you're actually using, while `rbenv-gemset` organizes them into separate gemsets).
* I know I can trust `rbenv-gemset` to do what it needs to do because its codebase is simpler, and its separation is rock-solid, relying on the separation that `gem` guarantees you. This point was brought home to me some time back, because `bundler` couldn't handle a particular combination of gems being installed together at the same time. Admittedly not `bundler`'s fault, because it was a situation of different gem versions overwriting each other's binaries... but you get the picture. Sometimes you really do need "gemset-level" separation.

If you're an active user of `rbenv-gemset`, that would be great.

**Comment by radriaanse** [comment]
I'm not a long-term user yet. I started using it a couple of weeks ago to solve some problems I had with rvm on my production env. I will probably keep using it, so after I get some more hands-on I will start with writing some docs.

**Comment by jf** [comment]
Coming back to this long-time issue: I hope the latest patches address this for everybody? If anybody still has any problems with the documentation, feel free to send in your patches. I'll close this issue in a couple of days if I don't hear anything in this thread.
