### ISSUE TITLE
Not sure why rbenv-gemset isn't working with tmuxinator

### ISSUE THREAD

**Issue by asgeo1** [jf/rbenv-gemset#80]
Hi there,

I'm trying to use rbenv-gemset with tmuxinator.

I have a project specific gemset:

    # .rbenv-gemsets
    .gems

And a basic tmuxinator config:

    name: myproject
    root: ~/Projects/myproject

    windows:
      - editor: vim
      - server: foreman start

If I run `tmuxinator start myproject` from any directory (other than the project directory), then I start getting "gem not found" errors:

Looking at `gem env`, then I can see that rbenv-gemset hasn't been configured:

    →  myproject git:(master) × gem env
    RubyGems Environment:
      - RUBYGEMS VERSION: 2.6.7
      - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [x86_64-darwin15]
      - INSTALLATION DIRECTORY: /Users/asgeo1/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0
    ...

However, if I `cd` to `~/Projects/myproject` *first*, and then run `tmuxinator start myproject`, then tmuxinator works fine, and the windows can find the gems in the gemset.

The `gem env` also reports the expected settings:

    →  myproject git:(master) × gem env
    RubyGems Environment:
      - RUBYGEMS VERSION: 2.6.7
      - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [x86_64-darwin15]
      - INSTALLATION DIRECTORY: /Users/asgeo1/Projects/myproject/.gems
    ...

So I don't understand why it doesn't work when I *don't* cd to the project directory before starting tmuxinator.

Is there a command I can run, (which I could put into the tmuxinator config), that would "activate" a particular gemset?

Kind of like how you can do this in tmuxinator:

    # Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
    pre_window: rbenv shell 2.0.0-p247

I'm not sure... It's just odd that rbenv-gemset won't work with tmuxinator.   It's probably a tmuxinator issue, but I thought I would ask here first.

**Comment by asgeo1** [comment]
Actually, I think I have it working now.  I added this into the project tmuxinator settings:

    # Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
    pre: export RBENV_GEMSET_ALREADY=no

Seems to slow down the starting of each tmuxinator window a bit, but otherwise seems to work.

Happy to hear any better suggestions if there are any.

**Comment by jf** [comment]
hi, @asgeo1 . Happy to see you fixed it on your own!

I'm not familiar with tmuxinator, but based on the behaviour you're seeing, it looks like (and looking at tmuxinator's own code characteristics would probably confirm it, it being mainly written in ruby) the windows are being spawned *from* a running ruby process.

`RBENV_GEMSET_ALREADY` is actually used to shortcut the rbenv execution process (see a324d6404290e42f4c593f2058fbfd0fb44837ba) and reduce unnecessary recursive calls to `rbenv-gemset`. In the case of tmuxinator, because each window is created in the *environment* of the parent ruby process (this is my guess - but pls do confirm it by doing an `echo $RBENV_GEMSET_ALREADY` in each window without your export fix), `RBENV_GEMSET_ALREADY` will already be set to yes. `rbenv-gemset` sees that it has already run prior to this and set up a gem environment already (that of the the parent ruby process) and will shortcut itself and not do so again. If that existing gem environment was set up correctly... no problem. This is what's causing the difference between when you `cd`, and not `cd` into the project directory.

As for the slowdown... any slowdown would be due to tmuxinator having to do that `pre` call. This doesnt slow `rbenv-gemset` down at all (and as you can see, will in fact speed it up).

**Comment by asgeo1** [comment]
@jf - yes, you're right.

If I put this in my tmuxinator config:

    # Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
    pre_window: echo $RBENV_GEMSET_ALREADY

then it will echo `yes`


And if I start tmuxinator like this, it will start up correctly:

    RBENV_GEMSET_ALREADY=no tmuxinator start myproject


I guess it's a tmuxinator issue?  Not sure...  I might bring it up with them.  The export fix works pretty well though.

Thanks for your help!

**Comment by jf** [comment]
:) thanks for the feedback, @asgeo1 ! It's great to have my suspicions confirmed... I wouldnt see it so much as a tmuxinator issue, though. It's just an artifact of how it works (and `rbenv-gemset` being optimized).

> RBENV_GEMSET_ALREADY=no tmuxinator start myproject

Well now this is interesting! Would be worth finding out more about from the tmuxinator folks, in order to understand how they deal with environment variables. But I would do this more out of curiosity than anything else...

Good to know this just about settles things very nicely for you. If you do find out more about how tmuxinator works internally, be sure to let me know! :)
